// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: business/business_list_as_claim.proto

package business

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Business struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid        string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AccountName string   `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	NickName    string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Roles       []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *Business) Reset() {
	*x = Business{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_list_as_claim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Business) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Business) ProtoMessage() {}

func (x *Business) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_list_as_claim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Business.ProtoReflect.Descriptor instead.
func (*Business) Descriptor() ([]byte, []int) {
	return file_business_business_list_as_claim_proto_rawDescGZIP(), []int{0}
}

func (x *Business) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Business) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *Business) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *Business) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type BusinessListAsClaimResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Business []*Business `protobuf:"bytes,1,rep,name=business,proto3" json:"business,omitempty"`
}

func (x *BusinessListAsClaimResult) Reset() {
	*x = BusinessListAsClaimResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_list_as_claim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessListAsClaimResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessListAsClaimResult) ProtoMessage() {}

func (x *BusinessListAsClaimResult) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_list_as_claim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessListAsClaimResult.ProtoReflect.Descriptor instead.
func (*BusinessListAsClaimResult) Descriptor() ([]byte, []int) {
	return file_business_business_list_as_claim_proto_rawDescGZIP(), []int{1}
}

func (x *BusinessListAsClaimResult) GetBusiness() []*Business {
	if x != nil {
		return x.Business
	}
	return nil
}

type BusinessListAsClaimRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *BusinessListAsClaimRequest) Reset() {
	*x = BusinessListAsClaimRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_list_as_claim_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessListAsClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessListAsClaimRequest) ProtoMessage() {}

func (x *BusinessListAsClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_list_as_claim_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessListAsClaimRequest.ProtoReflect.Descriptor instead.
func (*BusinessListAsClaimRequest) Descriptor() ([]byte, []int) {
	return file_business_business_list_as_claim_proto_rawDescGZIP(), []int{2}
}

func (x *BusinessListAsClaimRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_business_business_list_as_claim_proto protoreflect.FileDescriptor

var file_business_business_list_as_claim_proto_rawDesc = []byte{
	0x0a, 0x25, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2f, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x61, 0x73, 0x5f, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x22, 0x74, 0x0a, 0x08, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x4b, 0x0a, 0x19, 0x42, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x73, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x08, 0x62, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x1a, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x73, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x6f, 0x0a, 0x13, 0x42,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x58, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x73, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x12, 0x24, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x42, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x73, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x73, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x75, 0x72, 0x69, 0x73,
	0x74, 0x69, 0x6b, 0x72, 0x6f, 0x74, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_business_business_list_as_claim_proto_rawDescOnce sync.Once
	file_business_business_list_as_claim_proto_rawDescData = file_business_business_list_as_claim_proto_rawDesc
)

func file_business_business_list_as_claim_proto_rawDescGZIP() []byte {
	file_business_business_list_as_claim_proto_rawDescOnce.Do(func() {
		file_business_business_list_as_claim_proto_rawDescData = protoimpl.X.CompressGZIP(file_business_business_list_as_claim_proto_rawDescData)
	})
	return file_business_business_list_as_claim_proto_rawDescData
}

var file_business_business_list_as_claim_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_business_business_list_as_claim_proto_goTypes = []interface{}{
	(*Business)(nil),                   // 0: business.Business
	(*BusinessListAsClaimResult)(nil),  // 1: business.BusinessListAsClaimResult
	(*BusinessListAsClaimRequest)(nil), // 2: business.BusinessListAsClaimRequest
}
var file_business_business_list_as_claim_proto_depIdxs = []int32{
	0, // 0: business.BusinessListAsClaimResult.business:type_name -> business.Business
	2, // 1: business.BusinessListService.ListAsClaim:input_type -> business.BusinessListAsClaimRequest
	1, // 2: business.BusinessListService.ListAsClaim:output_type -> business.BusinessListAsClaimResult
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_business_business_list_as_claim_proto_init() }
func file_business_business_list_as_claim_proto_init() {
	if File_business_business_list_as_claim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_business_business_list_as_claim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Business); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_list_as_claim_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessListAsClaimResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_list_as_claim_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessListAsClaimRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_business_business_list_as_claim_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_business_business_list_as_claim_proto_goTypes,
		DependencyIndexes: file_business_business_list_as_claim_proto_depIdxs,
		MessageInfos:      file_business_business_list_as_claim_proto_msgTypes,
	}.Build()
	File_business_business_list_as_claim_proto = out.File
	file_business_business_list_as_claim_proto_rawDesc = nil
	file_business_business_list_as_claim_proto_goTypes = nil
	file_business_business_list_as_claim_proto_depIdxs = nil
}
