// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: business/business_list_as_claim.proto

package business

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BusinessListServiceClient is the client API for BusinessListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BusinessListServiceClient interface {
	ListAsClaim(ctx context.Context, in *BusinessListAsClaimRequest, opts ...grpc.CallOption) (*BusinessListAsClaimResult, error)
}

type businessListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessListServiceClient(cc grpc.ClientConnInterface) BusinessListServiceClient {
	return &businessListServiceClient{cc}
}

func (c *businessListServiceClient) ListAsClaim(ctx context.Context, in *BusinessListAsClaimRequest, opts ...grpc.CallOption) (*BusinessListAsClaimResult, error) {
	out := new(BusinessListAsClaimResult)
	err := c.cc.Invoke(ctx, "/business.BusinessListService/ListAsClaim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessListServiceServer is the server API for BusinessListService service.
// All implementations must embed UnimplementedBusinessListServiceServer
// for forward compatibility
type BusinessListServiceServer interface {
	ListAsClaim(context.Context, *BusinessListAsClaimRequest) (*BusinessListAsClaimResult, error)
	mustEmbedUnimplementedBusinessListServiceServer()
}

// UnimplementedBusinessListServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBusinessListServiceServer struct {
}

func (UnimplementedBusinessListServiceServer) ListAsClaim(context.Context, *BusinessListAsClaimRequest) (*BusinessListAsClaimResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAsClaim not implemented")
}
func (UnimplementedBusinessListServiceServer) mustEmbedUnimplementedBusinessListServiceServer() {}

// UnsafeBusinessListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusinessListServiceServer will
// result in compilation errors.
type UnsafeBusinessListServiceServer interface {
	mustEmbedUnimplementedBusinessListServiceServer()
}

func RegisterBusinessListServiceServer(s grpc.ServiceRegistrar, srv BusinessListServiceServer) {
	s.RegisterService(&BusinessListService_ServiceDesc, srv)
}

func _BusinessListService_ListAsClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessListAsClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessListServiceServer).ListAsClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.BusinessListService/ListAsClaim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessListServiceServer).ListAsClaim(ctx, req.(*BusinessListAsClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BusinessListService_ServiceDesc is the grpc.ServiceDesc for BusinessListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusinessListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "business.BusinessListService",
	HandlerType: (*BusinessListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAsClaim",
			Handler:    _BusinessListService_ListAsClaim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "business/business_list_as_claim.proto",
}
